spring:
  application:
    name: BookingSystem

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: 127lg573im3179uwus1703ni228js642ca22z5a17483bf
  lifetime: 48h

server:
  port: 8080