spring:
  application:
    name: BookingSystem

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${SECRET}
  lifetime: 48h

server:
  port: 8080

WEBAPP_LINK: ${WEBAPP_LINK}