client-id: BookingSystem
resource-url: http://localhost:8080/realms/BookingSystem/protocol/openid-connect/token
grant-type: password

spring:
  application:
    name: BookingSystem

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: BookingSystem
            authorization-grant-type: authorization_code
            scope:
              - openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/BookingSystem
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/BookingSystem

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8000